
services:
  elasticsearch:
    build: ./docker/elasticsearch
    container_name: es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports: ["9200:9200"]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 30

  kibana:
    build: ./docker/kibana
    container_name: kib
    depends_on: [elasticsearch]
    ports: ["5601:5601"]
    
  syslog:
    build: ./docker/syslog
    container_name: syslog
    depends_on: [elasticsearch]
    ports: ["5514:5514/udp"]
    environment:
      - ES_URL=http://elasticsearch:9200
    volumes:
      - ./docker/syslog/config/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      

  ids:
    build: ./docker/ids
    container_name: ids
    depends_on:
      - syslog
    environment:
      - SYSLOG_HOST=syslog
      - SYSLOG_PORT=5514
    volumes:
      - ./docker/ids/config:/etc/snort:ro
